### ISSUE TITLE
When saving nested_form_fields console stays BEGIN

### ISSUE THREAD

**Issue by superrandres** [ncri/nested_form_fields#74] opened 2016-08-19 23:13 UTC
Hi friends, I need your help please. I'm using the gem 'nested_form_fields' and 'mysql2', no problem could save by creating a new record or update it. I have been improving much the HTML interface several days and today I find the news that I can just update a record and not create a new one with other nested records. This leaves me in the console and stays there. As if doing something or as if stopped by a breakpoint.

I've already tried changing the settings:
tx_isolation of REPEATABLE-READ to READ-UNCOMMITTED in MySQL
Attached a picture of the console.

![errorconsola](https://cloud.githubusercontent.com/assets/8306417/17826586/e9097bb6-6637-11e6-9736-fc5c11d439f3.png)
![relaciones](https://cloud.githubusercontent.com/assets/8306417/17826637/66de5728-6638-11e6-91f2-e937d904bdfa.png)

![entidad](https://cloud.githubusercontent.com/assets/8306417/17826603/163b2b7a-6638-11e6-9423-f9eae5b9ec7c.png)

**Comment by ncri** [comment] 2016-08-20 06:01
So the record saves, but not the nested ones? And the action just hangs and never returns when saving? It's difficult to see for me what's going on as I don't have enough infos about your app. If you think this is database related you could try postgres or sqlite and see if the issue is there too. But I'm not sure if the DB is the issue here.

**Comment by superrandres** [comment] 2016-08-22 22:09
Hello friend, yes, when I try to create a new record if I put other records nested then the WEBrick server stops and stays in BEGIN, as you can see on the console starts making the insert from the main table but stays there.

I tried but I had to migrate SQLite3 many data tables and finally I did it and thank God it works but do not understand why not come out with MySQL. As I said at the beginning it worked very well but now apparently play something but can not be.

I appreciate the advice to try with another DB...

**Comment by ncri** [comment] 2016-11-11 20:18
I'll close this as it seem unrelated to the nested_form_fields gem.

**Closed by ncri** 2016-11-11 20:18 UTC
